server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.196.148.78:3306/vueblog?useSSL=false&useUnicode=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Admin123~.
  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    #在控制台输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization

shiro-reids:
  enabled: true
  redis-manager:
    host: 121.196.148.78:6379



